const QM_CADENCES={'daily':'일일','weekly':'1주 / 1회','biweekly':'2주 / 1회','monthly':'월 / 1회','yearly':'연 / 1회'};
const QM_SCHEDULE_LOGS=['공정점검일지','작업장위생점검일지','중량점검일지'];
function readSchedules(){try{return JSON.parse(localStorage.getItem('qm-journal-schedules-v1')||'{}')}catch{return {}}}
function cadenceLabel(name){const s=readSchedules()[name];return QM_CADENCES[s?.frequency]||'작성주기 미설정'}
function nextScheduledDate(start,frequency,today){
 if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!QM_CADENCES[frequency])return '';
 const base=new Date(start+'T00:00:00Z'),now=new Date(today+'T00:00:00Z');if(!Number.isFinite(+base)||!Number.isFinite(+now))return '';if(base>=now)return start;
 const days={daily:1,weekly:7,biweekly:14}[frequency];if(days){base.setUTCDate(base.getUTCDate()+Math.ceil((now-base)/(86400000*days))*days);return base.toISOString().slice(0,10)}
 const month=base.getUTCMonth(),day=base.getUTCDate(),year=base.getUTCFullYear();let n=frequency==='monthly'?(now.getUTCFullYear()-year)*12+now.getUTCMonth()-month:now.getUTCFullYear()-year;
 function at(index){const target=new Date(Date.UTC(year+(frequency==='yearly'?index:0),month+(frequency==='monthly'?index:0),1));const last=new Date(Date.UTC(target.getUTCFullYear(),target.getUTCMonth()+1,0)).getUTCDate();target.setUTCDate(Math.min(day,last));return target}
 let target=at(n);if(target<now)target=at(n+1);return target.toISOString().slice(0,10);
}
function renderScheduleSettings(container,today,onSaved){
 container.classList.add('qm-settings');const existing=readSchedules();container.innerHTML='<div class="qm-setting-intro"><h2>작성주기 설정</h2><p>일지별 주기와 최초 기준일을 정해주세요. 월말 날짜는 해당 월의 마지막 날에 맞춥니다.</p></div>';const inputs=[];
 QM_SCHEDULE_LOGS.forEach(name=>{const current=existing[name]||{},row=document.createElement('section');row.className='qm-setting-row';const title=document.createElement('strong');title.textContent=name;const frequencyLabel=document.createElement('label');frequencyLabel.textContent='작성주기';const select=document.createElement('select');[['','미설정'],...Object.entries(QM_CADENCES)].forEach(([value,label])=>{const o=document.createElement('option');o.value=value;o.textContent=label;select.append(o)});select.value=current.frequency||'';frequencyLabel.append(select);let start=current.startDate||today;const startLabel=document.createElement('label');startLabel.textContent='최초 기준일';const date=qcDateInput(start,false,v=>{start=v;preview()});startLabel.append(date);const hint=document.createElement('small');hint.className='qm-due';function preview(){const next=nextScheduledDate(start,select.value,today);hint.textContent=next?'다음 예정일: '+displayQcDate(next):'주기를 선택해주세요.';date.required=!!select.value}select.onchange=preview;row.append(title,frequencyLabel,startLabel,hint);container.append(row);inputs.push({name,select,date,start:()=>start});preview()});
 const footer=document.createElement('div');footer.className='qm-setting-footer';const save=document.createElement('button');save.type='button';save.className='primary';save.textContent='주기 설정 저장';const status=document.createElement('span');status.setAttribute('role','status');save.onclick=()=>{const changes={...readSchedules()};for(const item of inputs){if(item.select.value){if(!item.date.reportValidity())return;const parsed=parseQcDate(item.start());if(!parsed.valid||!parsed.iso){item.date.focus();status.textContent='기준일을 확인해주세요.';return}changes[item.name]={frequency:item.select.value,startDate:parsed.iso}}else delete changes[item.name]}try{localStorage.setItem('qm-journal-schedules-v1',JSON.stringify(changes));onSaved();const message=document.getElementById('qmScheduleMessage');if(message)message.textContent='주기 설정을 이 기기에 저장했습니다.'}catch{status.textContent='저장하지 못했습니다. 기기의 저장 공간을 확인해주세요.'}};status.id='qmScheduleMessage';footer.append(save,status);container.append(footer);
 const note=document.createElement('p');note.className='qm-footnote';note.textContent='예정일은 설정한 주기로 계산합니다. 임시저장만으로 완료 처리하지 않으며, 완료·미작성 판정은 후속 연결 대상입니다.';container.append(note);
}
